apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongo.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    chart: {{ template "backendapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo